### ISSUE TITLE
Ztree>3.5.2>excheck.js 打包后的好像有bug，-debug版本的没有问题

### ISSUE THREAD

**Issue by minuux** [cmdjs/gallery#16]
![ztree-excheck-bug](https://f.cloud.github.com/assets/1884625/434105/e984198e-af15-11e2-8f92-706d29ffe484.png)

截图是实现 Ztree中自带的例子 excheck/checkbox.html，有多余的checkbox产生,有些事件也不会触发了

**Comment by afc163** [comment]
请使用最新的版本。
