### ISSUE TITLE
Handlebars 模块的版本不对

### ISSUE THREAD

**Issue by edokeh** [cmdjs/gallery#20]
通过spm下载最新版本是 1.0.2，但是打开源文件发现是 1.0.0 rc4

看到这个文件里面有个 version2 ，而 grunt 也是下载的 version2 ，不知是何意？
https://github.com/cmdjs/gallery/blob/master/handlebars/package.json

**Comment by popomore** [comment]
因为第一步就走错了，rc 的时候就用的 1.0.0

**Comment by edokeh** [comment]
果然是这样。。。
那现在要怎么办？Handlebars 已经有 1.0.0 正式版了

**Comment by popomore** [comment]
自暴自弃的等待 1.0.3

**Comment by edokeh** [comment]
好吧，那我只好在私服上自己弄个正确版本的 Handlebars 了
刚去看了下它的 repo 居然有 1.0.12 的 tag，怪事
https://github.com/wycats/handlebars.js/tree/v1.0.12

**Comment by popomore** [comment]
1.0.12 应该是 node 版的

**Comment by popomore** [comment]
handlebars 已经 1.3.0 了，1.1 以后的版本就合并了 https://github.com/wycats/handlebars.js/issues/549
