### ISSUE TITLE
封装 angular

### ISSUE THREAD

**Issue by popomore** [cmdjs/gallery#21]
@leoner 这个能封装么？

**Comment by leoner** [comment]
我看看, 应该可以.

**Comment by leoner** [comment]
@popomore  angular 是不是应该和 jquery 一样? 作为一个 family?

**Comment by popomore** [comment]
先总结下封装和使用的最佳实践好了，放在哪都好说。

**Comment by lifesinger** [comment]
应该是一个新的 family

放 https://github.com/cmdjs/angular 下面

On Fri, Jul 19, 2013 at 1:46 PM, Haoliang Gao notifications@github.comwrote:

> 先总结下封装和使用的最佳实践好了，放在哪都好说。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmdjs/gallery/issues/21#issuecomment-21232513
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by popomore** [comment]
那玉伯要建个库，加下权限

**Comment by lifesinger** [comment]
你们都是 owner 了

On Fri, Jul 19, 2013 at 4:01 PM, Haoliang Gao notifications@github.comwrote:

> 那玉伯要建个库，加下权限
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmdjs/gallery/issues/21#issuecomment-21236648
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
@lifesinger   https://github.com/cmdjs/angular  没有此项目呀.

**Comment by lepture** [comment]
@leoner 建了一个

**Comment by leoner** [comment]
已封装

```
spm info angular/angularjs
```
