### ISSUE TITLE
引入 bootstrap v3.0

### ISSUE THREAD

**Issue by afc163** [cmdjs/gallery#24]
等待正式发布。

**Comment by afc163** [comment]
- [x] hightcharts

**Comment by lizzie** [comment]
- [x] bootstrap v3.0 https://github.com/twbs/bootstrap/

**Comment by afc163** [comment]
官方已发布 https://github.com/twbs/bootstrap/tree/v3.0.0

**Comment by lizzie** [comment]
https://spmjs.org/gallery/bootstrap/

**Comment by afc163** [comment]
spmjs 页面看不到 bootstrap.js bootstrap.css 这两个输出，是个问题。

**Comment by lizzie** [comment]
另外想起来一个问题, bootstrap.css 中用到了 iconfont, 字体文件在 fonts/ 下, 如果部署上去, 应该也是会碰到 firefox 下没法正确显示图标的问题, 需要服务器端设置 iconfont 的 access-allow-origin: \*

**Comment by popomore** [comment]
@afc163 spmjs 也可以和 status 一样把包里的文件显示出来？

@lizzie 这个可以找南伯配下吧
