### ISSUE TITLE
bootstrap 3.0 缺少 bootstrap-theme.css

### ISSUE THREAD

**Issue by atans** [cmdjs/gallery#26]
gallery/bootstrap
https://github.com/cmdjs/gallery/tree/master/bootstrap

see https://github.com/twbs/bootstrap/tree/master/dist/css

Thanks

**Comment by popomore** [comment]
https://github.com/cmdjs/gallery/blob/master/bootstrap/dist/bootstrap.css

不是这个么

**Comment by afc163** [comment]
@lizzie 补之。
