### ISSUE TITLE
加入 Respond.js

### ISSUE THREAD

**Issue by atans** [cmdjs/gallery#27]
Bootstrap 3.0 加入Respond.js

@see https://github.com/scottjehl/Respond

A fast & lightweight polyfill for min/max-width CSS3 Media Queries (for IE 6-8, and more)

不知道 cmdjs/gallery 能否加上

Thanks

**Comment by afc163** [comment]
欢迎 PR

**Comment by atans** [comment]
不太會用cmjs/gallery/_task 下載文件

你測試了一下bootstrap, 顯示以下錯誤

$ cd /path/to/gallery
$ npm install grunt --save-dev <-- 這個需要嗎？
$ cd bootstrap
$ grunt default

```
Loading "download.js" tasks...ERROR
>> Error: Cannot find module 'request'
Warning: Task "download" not found. Use --force to continue.


Aborted due to warnings.
```

**Comment by afc163** [comment]
按这个来 https://github.com/cmdjs/gallery#%E5%BC%95%E5%85%A5-cmd-%E6%A8%A1%E5%9D%97%E6%8C%87%E5%8D%97

**Comment by atans** [comment]
@afc163 我跟著文檔做的. 写完Gruntfile.js之后, 就执行 `grunt`, 接著報錯:

![2013-09-06_174153](https://f.cloud.github.com/assets/2189764/1094933/9be0a668-16d8-11e3-9bc0-36557a53460a.jpg)

```
Loading "download.js" tasks...ERROR
>> Error: Cannot find module 'request'
Warning: Task "download" not found. Use --force to continue.


Aborted due to warnings.
```

**Comment by atans** [comment]
原來要先執行: npm install -g request

**Comment by atans** [comment]
https://github.com/scottjehl/Respond/blob/master/respond.src.js

@afc163 
不知道respond 要不要 加 `define(function(require, exports, module) {`

download task 需要這樣設定嗎?

```
options: {
                    transform: function(code) {
                        return [
                            'define(function(require, exports, module) {',
                            code,
                            "});"
                        ].join('\n');
                    }
                }
}
```
