### ISSUE TITLE
html5shiv

### ISSUE THREAD

**Issue by lepture** [cmdjs/gallery#3]
alipay.com 首页用的 html5shiv 是个 hack 版，完全看不懂。

https://github.com/aFarkas/html5shiv 这个看起来就能看懂了，transport 这个吧。

**Comment by lifesinger** [comment]
南伯搞下，这个不错的

On Mon, Dec 3, 2012 at 9:28 PM, Hsiaoming Yang notifications@github.comwrote:

> alipay.com 首页用的 html5shiv 是个 hack 版，完全看不懂。
> 
> https://github.com/aFarkas/html5shiv 这个看起来就能看懂了，transport 这个吧。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seajs/gallery/issues/3.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
