### ISSUE TITLE
spm 找不到 html5shiv

### ISSUE THREAD

**Issue by atans** [cmdjs/gallery#30]
$ spm info gallery/html5shiv

  gallery/html5shiv
  not found

是不是沒有推送到spm, 還是？
還有最新版本是 `3.6.2`

Thanks

**Comment by afc163** [comment]
自己搞一个发到 spmjs.org 

在 2013-9-10，下午12:14，Atans notifications@github.com 写道：

**Comment by atans** [comment]
@afc163 問題是 cmdjs/gallery 本身就有 html5shiv
@see https://github.com/cmdjs/gallery/tree/master/html5shiv

但是 spm 搜索不到gallery/html5shiv

**Comment by atans** [comment]
明白了，刚学会发布到spmjs.org
Thanks
