### ISSUE TITLE
希望 cmdjs/gallery/_tasks/download/tasks/download.js 能够成为gurnt的插件

### ISSUE THREAD

**Issue by atans** [cmdjs/gallery#31]
@see https://github.com/cmdjs/gallery/blob/master/_tasks/download/tasks/download.js

如果能够成为gurnt-cmd-download的插件， 就不用每个项目都复制`_tasks/download`

Thanks

**Comment by afc163** [comment]
https://github.com/twolfson/grunt-curl/ 这个就是。

**Comment by afc163** [comment]
好像不完全一样，楼主也可以自己封装一个，发布到 npm 。

**Comment by atans** [comment]
好吧，我试试

**Comment by atans** [comment]
@afc163 
我簡單的封装了 `Hsiaoming Yang` 寫的 cmdjs/gallery/_tasks/ download 到 npm
不知道這樣做有沒有問題 ?

https://npmjs.org/package/grunt-downloader

**Comment by lepture** [comment]
@atans remove this line: https://github.com/atans/grunt-downloader/blob/master/tasks/downloader.js#L68

**Comment by atans** [comment]
Updated, thanks
原來 @lepture  就是Hsiaoming Yang, 久仰大名
