### ISSUE TITLE
Bootstrap 3 font 文件不對應

### ISSUE THREAD

**Issue by atans** [cmdjs/gallery#36]
https://github.com/cmdjs/gallery/tree/master/bootstrap/dist/fonts

如： 
glyphicons-halflings-regular.eot

file 138 lines (137 sloc) 25.253 k
https://github.com/cmdjs/gallery/blob/master/bootstrap/dist/fonts/glyphicons-halflings-regular.eot

vs

file 14.079 kb 
https://github.com/twbs/bootstrap/blob/v3.0.0/dist/fonts/glyphicons-halflings-regular.eot

下載下來後文件變大了。
ttf文件也打不開

**Comment by lizzie** [comment]
嗯, sorry, 现在才看到这个 issue, 字体文件已经更新~

**Comment by atans** [comment]
@lizzie

還是沒有解決
request下載的字體文件大小改變了，導致無法使用

左面是官方的3.0.2,右面是grunt下載的
![2013-11-09_143636](https://f.cloud.github.com/assets/2189764/1506072/6c63554e-4909-11e3-80a5-127d6ca3e54c.jpg)

**Comment by lizzie** [comment]
gruntfile.js 中的路径下载下来确实不对, 不知为何, 同一路径的, 直接浏览器下载字体文件是对的, grunt 就不行. 

spmjs 上的字体是对的, 当时我手工下载并 publish 了的.
