### ISSUE TITLE
描述是否能支持中文

### ISSUE THREAD

**Issue by afc163** [cmdjs/gallery#4]
尤其是在 aralejs.org 的首页。

**Comment by lifesinger** [comment]
觉得可以，package.json 应该是开放的，什么语言都支持

On Wed, Dec 5, 2012 at 12:11 AM, afc163 notifications@github.com wrote:

> 尤其是在 aralejs.org 的首页。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seajs/gallery/issues/4.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lepture** [comment]
@afc163 都是别人原来的 description。最好不要改啦。

**Comment by lifesinger** [comment]
用中文吧，等有老外用户时，我们再考虑推出英文版。

On Wed, Dec 5, 2012 at 12:03 PM, Hsiaoming Yang notifications@github.comwrote:

> @afc163 https://github.com/afc163 都是别人原来的 description。最好不要改啦。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seajs/gallery/issues/4#issuecomment-11028322.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lepture** [comment]
@lifesinger 用中文要自己一个个的改耶，这里是 gallery，不是 arale。

**Comment by lifesinger** [comment]
gallery 的就保持原来是什么就是什么好了

南伯把 calendar 的改掉，现在那句英文介绍好挫

On Wed, Dec 5, 2012 at 1:07 PM, Hsiaoming Yang notifications@github.comwrote:

> @lifesinger https://github.com/lifesinger 用中文要自己一个个的改耶，这里是 gallery，不是
> arale。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seajs/gallery/issues/4#issuecomment-11029868.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
