### ISSUE TITLE
masonry封装

### ISSUE THREAD

**Issue by lcat** [cmdjs/gallery#42]
[https://github.com/desandro/masonry/blob/master/masonry.js](https://github.com/desandro/masonry/blob/master/masonry.js)

```
 ( function( window ) {
  function masonryDefinition( Outlayer, getSize ) {
    var Masonry = Outlayer.create('masonry');
    code...
    return Masonry;
 }
 if ( typeof define === 'function' && define.amd ) {
   // AMD
   define( [
     'outlayer/outlayer',
     'get-size/get-size'
   ],
  masonryDefinition );
 } else {
   // browser global
    window.Masonry = masonryDefinition(
      window.Outlayer,
      window.getSize
    );
 }
 })( window );
```

我直接头尾加define封下，return Masonry； 改为 module.exports = Masonry;但是报错object is not a function 。。我哪里错了？谢谢~

**Comment by popomore** [comment]
有你封装的代码么？

**Comment by lcat** [comment]
[https://github.com/lcat/masonry/blob/master/dist/masonry-debug.js](https://github.com/lcat/masonry/blob/master/dist/masonry-debug.js)

**Comment by popomore** [comment]
没有调用 `masonryDefinition` 吧
