### ISSUE TITLE
store模块的依赖问题

### ISSUE THREAD

**Issue by lianqin7** [cmdjs/gallery#6]
如题，store模块其实隐式的依赖到了JSON对象，而在package里没有指定，导致在低级浏览器下运行出错

P.S. 用seajs的preload不算通用式的解决方案，为了组件的通用性，个人还是希望能在package里去指定依赖

@lepture

**Comment by lianqin7** [comment]
关于preload的问题，
因为preload是在所有模块之间就要加载好的，那么有2种情况
1. preload的文件combo在一起，这样为会增加初始加载文件的物理大小
2. preload的文件自由加载，那会肯定会增加其他模块的开始时间

**Comment by lizzie** [comment]
spmjs 上 gallery/store@1.3.14 加入了 依赖 gallery/json@1.0.3
