### ISSUE TITLE
请教Highcharts组建如何seajs化，多次尝试都失败了

### ISSUE THREAD

**Issue by larrykoo711** [cmdjs/gallery#8]
请教Highcharts组建如何seajs化，多次尝试都失败了

**Comment by lepture** [comment]
@gumutianqi highcharts 是非开源的，不能迁移过来的。

**Comment by larrykoo711** [comment]
但是个人是免费使用的，这个图表组件还是使用人比较多， 能提供一个seajs的模块化么方式么

**Comment by lepture** [comment]
@gumutianqi 
1. 免费不代表可以修改代码，这里说明一下。虽然 highcharts 是允许修改代码的 via http://shop.highsoft.com/highcharts.html#non-commercial
2. highcharts 是不会进入 gallery 的
3. 推荐直接使用

**Comment by larrykoo711** [comment]
自己坐测试，希望可以研究一下。
如果直接使用，那不是会加载两个jQuery，一个seajs的jquery，一个不是，怎么处理呢

**Comment by lepture** [comment]
@gumutianqi 可把 seajs.use 的 jQuery 暴露出去。

**Comment by popomore** [comment]
看来问题已经解决
